---
title: "Plots for radiative transfer plot"
author: Simone Massaro
date: 01/02/21
output: html_notebook
---
```{r}
library(tidyverse)
```
```{r}
dt <- 3600
source("setup_parameters.R")
source("fun_calc_radiative_transfer.R")
```
```{r}
library(readxl)
```
```{r}
path <- "../data/FLX_DE-Hai_FLUXNET2015_FULLSET_HH_2016-2018_beta-3_for_class.xlsx"
read_fluxnet_data <- function(path) {
  read_excel(path, na = "-9999") %>%
    select("Date/Time", SW_IN_F, SW_DIF, SW_OUT, LW_IN_F, LW_OUT, TS_F_MDS_1, TA_F, NIGHT) %>% # Columns interesting for radiative model
    rename(datetime = "Date/Time") %>%
    transmute(datetime = force_tz(datetime, "Etc/GMT+1" ),
              sw_dif = SW_DIF,
              sw_in = SW_IN_F,
              lw_in = LW_IN_F,
              t_leaf = 273.15 + TA_F,       # Temperature of air aproximation for leaf T for now
              t_soil = TS_F_MDS_1 + 273.15,
              sw_out = SW_OUT,
              lw_out = LW_OUT
    )
}
full_input <- read_fluxnet_data(path)
```
```{r}
input <- filter(full_input, datetime < as_date("2017-01-01"))
state <- tibble(t_leaf = input$t_leaf, t_soil = input$t_soil)
```
```{r}
library(progress)
pb <- progress_bar$new(format = "(:spin) [:bar] :percent [Elapsed time: :elapsedfull || Estimated time remaining: :eta]",
                       total = length(input$datetime),
                       clear = FALSE)
rad_transf <- function(){
  out <- data.frame()
  for (i in seq_along(input$datetime)){
    rad<- fun_calc_radiative_transfer(input[i,], state[i,], pars, dt)
    out[i, names(rad)] <- rad
    pb$tick()
  }
  return(out)
}
```
```{r}
out <- rad_transf()
```
```{r}
days <- seq.Date(as.Date("2020-01-01"), as.Date("2020-12-31"), by=1)
LAI <- pmax(Vectorize(get_day_LAI, "datetime")
            (days, pars$max_LAI, pars$leaf_out, pars$leaf_full, pars$leaf_fall, pars$leaf_fall_complete), pars$min_radiation_PAI)

ggplot() + geom_line(aes(x=days, y=LAI))
```
### Shortwave
```{r}
ggplot() +
        geom_abline(intercept = 0, slope = 1, color = "red", size = .3) +
        geom_point(aes(x = out$i_up, y = input$sw_out)) +
        geom_smooth(aes(x = out$i_up, y = input$sw_out), method = 'lm')
```



