---
title: "Radiative transfer model sensitivity and calibration"
author: Simone Massaro
date: 30/01/21
output: html_notebook
---
```{r}
dt <- 3600
source("setup_sitedata.R")
source("setup_parameters.R")
source("fun_calc_radiative_transfer.R")
library(FME)
library(tidyverse)
```
```{r}
state <- tibble(t_leaf = input$tair, t_soil = fluxes$tsoil)
```
```{r}
#' merges two list, in case of conflicts uses the second list value
merge_lists <- function (list1, list2){
  l <- list1
  for (name in names(list2)){
    l[name] <- list2[name]
  }
  return(l)
}
```
```{r}
rad_trans_new_p <- function (new_p=list()){
  pars <- merge_lists(pars, new_p)
  out <- data.frame()
  for (i in seq_along(input$datetime)){
    rad<- fun_calc_radiative_transfer(input[i,], state[i,], pars, dt)
    out[i, names(rad)] <- rad
  }
  print(".") # Progress
  return(out)
}
```
```{r}
out <- rad_trans_new_p()
```



```{r}
sens_p_sw <- pars[c("rho_leaf", "tau_leaf", "alb_soil_b", "alb_soil_d", "max_LAI")]
sens_sw_model <-  function(pars) select(rad_trans_new_p(pars), "ic", "i_up")
sens_sw <- sensFun(rad_trans_new_p, sens_p_sw, map=NULL)
```
```{r}
sens_sum <- summary(sens_sw)
cbind(par = attr(sens_sum, "row.names"), sens_sum) #little hack because pycharm doesn't show row names properly
```

```{r}
invert_sens <- function(df){
    vars <- df$var
    pars <- names(df)
    df <- as.data.frame(t(df))
    df <- cbind(pars, df)
    names(df) <- c("var", vars)
    return(df[-1, ])
}
```
mean
```{r}
sens_sw %>% group_by(var) %>%
        summarize_all(mean) %>%
        select(-x) %>%
        invert_sens
```
L1 (according to FME paper)
```{r}
sens_sw %>% group_by(var) %>%
        summarize_all(function(x) mean(abs(x))) %>%
        select(-x) %>%
        invert_sens()
```
L2 (according to FME paper)
```{r}
sens_sw %>% group_by(var) %>%
        summarize_all(function(x) sqrt(mean(x^2))) %>%
        select(-x) %>%
        invert_sens()
```



we can see that the rho_leaf is much more important than the tau_leaf

```{r}
cal_p <- c(
  # NB those are test parameters that make the model work. Still need to validate that they make sense
  rho_leaf = 0.4,                     # Leaf reflectance
  tau_leaf = 0.1                     # Leaf transmittance
)

cal_p_lower <- c(
  # NB those are test parameters that make the model work. Still need to validate that they make sense
  rho_leaf = 0.37,                     # Leaf reflectance
  tau_leaf = 0.05                     # Leaf transmittance
)
cal_p_upper <- c(
  # NB those are test parameters that make the model work. Still need to validate that they make sense
  rho_leaf = 0.42,                     # Leaf reflectance
  tau_leaf = 0.2                    # Leaf transmittance
)
```
```{r}
model_cost <- function (params){
  out <- rad_trans_new_p(params)
  out <- rename(out,sw_out=i_up)
  modCost(out, fluxes, x="datetime", y="sw_out")
}
```
```{r}
out$time <- fluxes$time
```
```{r}
tout <- select(out, time, sw_out)
tflux <- select(fluxes, time, sw_out)
```
```{r}
modCost(tout, tflux, x="time", y="sw_out")
```
```{r}
#' Cost function for radiative transfer model
model_cost_sw <- function (params){
  out <- rad_trans_new_p(params)
  return(out$i_up - fluxes$sw_out)
}
```
```{r}
mfit_sw <- modFit(model_cost_sw, cal_p, cal_p_lower, cal_p_upper)
```
```{r}
summary(mfit_sw)
```
