---
title: "Soil Temperature"
output:
  html_document:
    df_print: paged
---
## Set up
```{r}
# Setup soil temperature calibration

### This section is same as the start of the Main.R file ---------------
### It loads packages, defines time units, and sets up site data and parameters

## Required packages
library(dplyr)
library(FME)

# Setting some time unit variables in unit seconds ----
t_units <- list(hour  = 3600,
                halfh = 1800,
                day   = 86400,
                month = 2592000,
                year  = 31536000)
dt <- t_units$hour # delta time: model time step

## Load and prepare input ----
source("setup_sitedata.R")

# example values for calibration
input$lw_out <- 0.95 * 5.670373e-8 * input$tair^4 # no data for lw_out, so making a rough approximation using tair
input$Rn <- input$sw_in + input$lw_in - fluxes$sw_out - input$lw_out

## Set initial values ----
initial_state <- list(Tsoil=fluxes$tsoil[1])  # initial value for volumetric water content of soil [m3 m-3]

## Load parameters and adjust units ----

parsfile <- "pars_soils.csv"
source("setup_parameters1.R")

```

## Main Function
```{r}
# Function calculating soil temperature changes

get_soiltemp <- function(input, pars, initial_state) {


#Here inputs needed are indicated to later be able to implement them within the formulas

# SD <- 0.6    #SD of soil layer
# theta.sat <- 0.482 # m3 m-3 Volumetric water content at saturation value taken from Bonan p. 120 (soil defined as clay based on grain size of climate data)
#theta.liq <- 0.35  # This value needs to be taken from the outcomes of soil moisture model
# BD <- 1.2 # g cm-3
Tsoil0 <- initial_state$Tsoil # K Initial Temperature of soil
# dt <- 1800 # time step in seconds to change time interval
# Cvwat <- 4.19  #MJ
# Cvsoil <- 1.926 #MJ
  
  list2env(pars, envir = environment())
  theta.liq <- fluxes$swc
#Thermal conductivity of dry soils 

Kdry <- ((0.135*BD)+ 64.7)/(2700 -(0.947*BD))


#The thermal conductivity of soil solids varies with the quartz content of soil. 
#The Johansen method described by Farouki:

Ksol <- (Kq^q) * (Ko^(1 - q))

#Thermal conductivity of saturated soil for unfrozen condicitions
Ksat <- (Ksol^(1 - theta.sat)) * Kwat^theta.sat
#dimensionless Kersten number Ke


#Following Heat capacity of our soil is calculated using equation 5.32

Tsoil <- rep(NA, nrow(input))

for(i in 1:nrow(input)) {
  
  #browser()
 
  Se <- theta.liq[i]/theta.sat #0.06 makes reference to the coarse-texture soil (Se>0.05)
  Ke <- 1.0 + (0.7*(log10(Se))) 
  
  #Finally, after calculating all components Thermal conductivity of soil is calculated
  
  K <- Kdry + (Ksat - Kdry) * Ke # W m-1 K-1                                         
  
  Cv  = (((1-theta.sat)*Cvsoil)+(theta.liq[i]*Cvwat))*1000000 #MJ m-3 K-1 * 1000000 to change to J m-3 K-1
  
  if(i==1){Tsoil.i <- Tsoil0} else{Tsoil.i <- Tsoil[i-1]}
  
  Tair <- input$tair[i]  #theta air reference height (K) it may be zero i think
  G <- K / (SD / 2) * (Tair - Tsoil.i) # W m-3 s-1  Equation 5.22 taken from Bonan p. 69 used for calculation of heat flux going into soil
  S <- K/(SD / 2) * (Tsubsoil - Tsoil.i) # W m-3 s-1 Same equation used for the calculation of the heat flux at the botton of the soil layer.
  
  
  Tsoil[i]  <- Tsoil.i + ( G / (Cv * SD) + S / (Cv * SD) ) * dt # K units, Equation 5.15 used for the calculation of change of T in soil

  
  }
output <- data.frame(Tsoil=Tsoil)
return(output)
}


```

## Residuals & cost function
```{r}
# fun_cost_soiltemperature.R


cost_soiltemperature1 <- function(pars_calib, params = pars) {
  print(pars_calib)
  #browser()
  for(i in names(pars_calib)) {params[[i]] <- pars_calib[[i]]}
  
  output <- get_soiltemp(input = input, initial_state = initial_state, pars = params)
  
  # Calculate residuals
  resid <- output$Tsoil - fluxes$tsoil
  resid <- resid[!is.na(resid)]
  
  return(resid)

}

```

## Sensitivity Analysis of Parameters
```{r}
## sensitivity analysis for soil temperature code parameters 
pars_full <- read.csv(parsfile)
# Parameters are extracted and then converted into a list for easy handling
pars <- pars_full$value
names(pars) <- pars_full$name
pars <- as.list(pars)
pars_sens <- c(Cvsoil=1.9, Ko=3, Tsubsoil=290)
Sens <- sensFun(cost_soiltemperature1, pars_sens)
summary(Sens)
plot(Sens$Cvsoil, ylim = c(-0.4, 0.5),main='Sensitivity Analysis', sub='Change over time',
     xlab='Flux in time', ylab='Range Values Sensitivity Function', col="blue", type = "l" )
lines(Sens$Ko, col="red")
legend("bottomright", inset=0.01, legend=c("Cvsoil", "Ko"), 
       lwd=2, cex=1.2, col=c("blue", "red"), bg="lightyellow")
plot(Sens$Tsubsoil,main='Sensitivity Analysis', sub='Change over time',
     xlab='Flux in time', ylab='Range Values Sensitivity Function', type = "l", col="orange")
legend("bottomright", inset=0.01, legend=c("Tsubsoil"),lwd=2, cex=1.2, col=c("orange"), bg="lightyellow")

```




## Calibration of Parameters
```{r}
# Soil temperature calibration
rm(list = ls())

parsfile <- "pars_soils.csv"

pars_calib <- c(Cvsoil=1.9, Ko=3, Tsubsoil = 290)
pars_low   <- c(Cvsoil=1.0, Ko=1, Tsubsoil = 280)
pars_high  <- c(Cvsoil=4.0, Ko=4, Tsubsoil = 300)
source("setup_soiltemperature_calib.R")
source("fun_soiltemperature1.R")
source("fun_costtemp1.R")

myfit <- modFit(f = cost_soiltemperature1,p = pars_calib, lower = pars_low, upper = pars_high)
plot(myfit)

summary(myfit)

```

## Runnin Model &  Parameters Not Calibrated
```{r}
parsfile <- "pars_soils.csv"
# Run model choosing parameter file
pars_full <- read.csv(parsfile)
# Parameters are extracted and then converted into a list for easy handling
pars1 <- pars_full$value
names(pars1) <- pars_full$name
pars1 <- as.list(pars1)

# Setup parameters


#source("setup_soiltemperature_calib.R")
source("fun_soiltemperature1.R")
Tsubsoil<-290
output1 <- get_soiltemp(input = input, initial_state = initial_state, pars = pars1)

plot(fluxes$tsoil, ylim = c(284, 292), type="l", main='Temperature data flux', sub='Change over time',
 xlab='Flux in time', ylab='Soil Temperature (K)')
plot(output1$Tsoil, ylim = c(284, 292), type="l",main='Temperature output model non-calibrated', sub='Change over time',
 xlab='Flux in time', ylab='Soil Temperature (K)')
```


## Running Model &  Parameters Calibrated
```{r}
# Run model choosing parameter file

parsfile <- "pars_soils_calib1.csv"
# Setup parameters

pars_full <- read.csv(parsfile)
# Parameters are extracted and then converted into a list for easy handling
pars <- pars_full$value
names(pars) <- pars_full$name
pars <- as.list(pars)

#source("setup_soiltemperature_calib.R")
source("fun_soiltemperature1.R")


output <- get_soiltemp(input = input, initial_state = initial_state, pars = pars)

plot(fluxes$tsoil, ylim = c(284, 292), type="l", main='Temperature data flux', sub='Change over time',
 xlab='Flux in time', ylab='Soil Temperature (K)')
plot(output$Tsoil, ylim = c(284, 292), type="l", main='Temperature output model calibrated', sub='Change over time',
 xlab='Flux in time', ylab='Soil Temperature (K)')


```

##Graph with results with calibrated & non-calibrated parameters
```{r}

plot(output$Tsoil, ylim = c(284, 292), col="blue", type="l",main='Comparison Outputs', sub='Change over time',
     xlab='Flux in time', ylab='Soil Temperature (K)')
lines(output1$Tsoil, ylim = c(284, 292), col="red")
lines(fluxes$tsoil, ylim=c(284, 292), col="green")
legend("bottomright", inset=0.01, legend=c("Pcalibrated", "PNon-Calibrated", "DataFlux"),lwd=2, cex=1.2, col=c("blue","red", "green"), bg="lightyellow")

plot(output$Tsoil, output1$Tsoil, type="l")
```

## Comparison of Data For Soil Temperature Data 
```{r}
## Plotting ##

library(ggplot2)
library(gridExtra)
library(tidyr)

Tsubsoil <- 283
output_cal <- get_soiltemp(input = input, initial_state = initial_state, pars = pars)

# Compare measured data to modeled data and pre-calibrated data

out_temp <- data.frame(fluxes$time, fluxes$tsoil, output_cal$Tsoil)
names(out_temp) <- c("time","MeasuredTsoil", "ModelSoilTemperature")

gg_temp <- gather(out_temp, key = "type", value = "temp", ModelSoilTemperature, MeasuredTsoil, factor_key = T)

ggplot() +
  geom_line(aes(x=gg_temp$time,y=gg_temp$temp, color = gg_temp$type), size = 1) +
  labs(y = "Soil Temperature [K]", x = "time", color = "")

```

